TodoListApp-Django/home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index")
]

TodoListApp-Django/todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("todos/", include("todos.urls")),
]

TodoListApp-Django/todos/urls.py
from django.urls import path

from . import views

app_name = "todos"

urlpatterns = [
    path("", views.todo_list, name="todo_list"),
    path("complete/<int:todo_id>/", views.complete, name="complete"),
    path("delete/<int:todo_id>/", views.delete, name="delete"),
]

TodoListApp-Django/home/models.py
from django.db import models

# Create your models here.

TodoListApp-Django/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    todo_name = models.CharField(max_length=100)
    added_date = models.DateTimeField(auto_now_add=True)
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return self.todo_name

TodoListApp-Django/home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(
        request,
        "home/index.html"
    )

TodoListApp-Django/todos/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404

from .models import Todo

# Create your views here.
def todo_list(request):
    status = request.GET.get("status", "not_completed")

    if status == "completed":
        todos = Todo.objects.filter(is_completed=True)

    else:
        todos = Todo.objects.filter(is_completed=False)

    if request.method == "POST":
        todo_name = request.POST.get("todo_name")
        
        if todo_name:
            Todo.objects.create(todo_name=todo_name)
            return redirect("todos:todo_list")
        
    return render(
        request,
        "todos/todo_list.html",
        {
            "todos": todos,
            "status": status
        }
    )

def complete(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)

    todo.is_completed = True
    todo.save()
    return redirect("todos:todo_list")

def delete(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.delete()
    return redirect("todos:todo_list")

TodoListApp-Django/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <title>Home</title>
</head>
<body>

    <div class="container">
        <h1>Hello World!</h1>

        <h2>Go to <a href="{% url 'todos:todo_list' %}">TodoList APP</a></h2>
    </div>
    
</body>
</html>

TodoListApp-Django/todos/templates/todos/todo_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'todos/style.css' %}">
    <title>TodoList APP</title>
</head>
<body>

    <div class="container">
        <h1>To-do List</h1>

        
        <form method="POST">
            {% csrf_token %}
            
            <input type="text" name="todo_name" placeholder="Register a new todo.">
            <button type="submit">Add</button>
            
        </form>

        <div class="filters">
            <a href="?status=completed">Ver concluídos</a>
            <a href="?status=not_completed">Ver Todos</a>
        </div>
        
        <ul>
            
            {% for todo in todos %}
                 
                <li>

                    {{ todo.todo_name }} | Added in:{{ todo.added_date }}
                    
                    {% if not todo.is_completed %}
                        <a class="btn complete" href="{% url 'todos:complete' todo.id %}">Concluir</a>
                    {% endif %}

                    <a class="btn delete" href="{% url 'todos:delete' todo.id %}" onclick="return confirm('Deseja realmente apagar?')">Deletar</a>

                </li>

            {% empty %}
            
                <li>There's no todo registered.</li>
            
            {% endfor %}
        </ul>

        <a href="{% url 'home:index' %}">Return to homepage</a>

    </div>
    
</body>
</html>